#
# Ansible managed
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-library
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: paperless-library
    namespace: home
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  capacity:
    storage: 5.5Ti
  local:
    path: /share/Files/PaperlessNGX
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - parche
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-library
  namespace: home
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5.5Ti
  storageClassName: local-storage
  volumeName: paperless-library
