---
collections:
  - name: community.general
    version: 6.4.0
  - name: community.sops
    version: 1.6.1
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.9.0
  - name: kubernetes.core
    version: 2.4.0
  - name: lvrfrc87.git_acp
    type: galaxy
