apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: layer2
  namespace: metallb-system
spec:
  ipAddressPools:
  - ingress-pool
  - general-pool
  interfaces:
  - br0
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: parche
