apiVersion: v1
data:
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:mbsew2FYmp65uQmv6N8b5uimKQBcdIjCYH1hMpzc76U63ntPTey2Sg==,iv:lXdk+J+d3pNbTqnoGneHTzE5EUynXj56ABhvD9DwtSs=,tag:2bxtEmi38vOkq7lBsfGPjg==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:WiI7DR7umNH2WNuGy9HzSasHqouh2IAHXXGkeHK9HpwhMTg+riX4Ag==,iv:ctoH9S2aEa3gi86/4T4XLF91ZGieslR8GQAutLdEC2s=,tag:OIaab/0O9VcDSIgUb1adGA==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:ZqmGuxX5FF9StNxKFVI2911dxXiW7eELoZbbTxLe3m6gGVb3xWUElA==,iv:URkVoeR7/mxqtpAe3iiTMv8x7mx4Kx75CrAZjSRzKt0=,tag:umMP9Vl2jTDKqnWaoY4f/g==,type:str]
    HOMEPAGE_VAR_READARR_API_KEY: ENC[AES256_GCM,data:kUo+RiiTA2VRluuiNU1EFuaL5FEL8dLPJgSGgChbChDFTACcYRpe2Q==,iv:W11Xbk7uVPhDbC7ruyu5UE7LWEOC6KtUx30ILNOc5zM=,tag:mt2OV9AUZWJB3cEXCFyoPA==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:JtmY545068ODFe2w2bZPQVs8LTHlrAR6ZBH7PYOhGh/ltZClHwYQ0Q==,iv:9vyuUJu3K3RhzS+KRxqPMMarbTVOn3tDvPBHP1AGR0c=,tag:OIyl2GbMYFPZyhGxbddPBw==,type:str]
    HOMEPAGE_VAR_IMMICH_API_KEY: ENC[AES256_GCM,data:RnkwPtGWC8YpHQplB/vjvzKdSPexhD8jNXbKtpZQHg72iJE7h7HCp+MkidRiyU0qTm/KDyIp734=,iv:Zk2aQaf3lZLnUBzAlQRGo8PL5tCMl9H0YOUwKtx5Pmk=,tag:aDIRY/Y6AjH3OnMLDI5unw==,type:str]
    HOMEPAGE_VAR_MEALIE_API_KEY: ENC[AES256_GCM,data:xV+ifWucRZsjIUF8pq8YmhlDF8DYFBOdPm3OQqaGNuMPfI6byb9wFKGzeh8Dd52tj7RlqOp19lr7+NnZsh1PDIf/V2oz6BrqGJIbedP3Ushmgc2Qe6qWyoanquYK8UUwTS4gqi7O11Io5zGqWrDBG97NGW7uSoeaTxcpxcxtYLt4vLWpb1zT4jhSbZiP2pmhKLJQa5xqggaDF1MuDo//7vwgh0v23vt/b4C8rlF4iYISGOd3VhfQ5OUTCkgsn6CjtkdhATcIYZi4e/WUvUUD5pwiSmOjAVGLJByLiFXP4xvav7+Nhed6hSI1RWz5Qwki2Jw52FSMoSc5M8MEjPpXIaUA0ANheJEHjlP9tIli1A5pxfgOK0ljLIt7VakPXBWFX5skRM+H4UTvvx7eG6wt3a6Q8Lr74VInDo9XybUd82QzgRJUUL4V/UL0M6c=,iv:yMqN17LFftkeIzpTjKTr5VnUpIqtK9icjXXN67qNWzU=,tag:wFs86b+c4o2s/GPK1MWZLg==,type:str]
    HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY: ENC[AES256_GCM,data:jmxDxVpcFB8pLsI17sfVt84/tg2rQI50rTeywQucV03o72xHRYB8qPI6NGYYB3kGP1TOp/0SwqJjWJ7S0tSvTiHtTcjK0bLCgmVjBZOlascMs1ymPhDOBclKcxrgM60KP+HnZI4P7IbBoOGJ2s7rbWPeawk3VItco8JeHNfYFS9FLEuJnIFntBOekqgPSlCfzFV8F41Z6NcqYvDee3V9b6k2wFY/7mfghX71x1l2xPwftkF+6WByw/tDHTiYUaNfaBWMgTdyNOHwb8+EFCcw3vQmJYWj7P5p5mFpLLL/NH/2lb+bXXdcolhtLGbNy1YCIkGVecfv6aHNUH2xtFiaGvFSJUY=,iv:QGVyNrnPB9AXHuRCXT+NsKX4Obwl9GZXth+ojUj/rfc=,tag:+C/AxklvC+vIliKnnjC1jA==,type:str]
    HOMEPAGE_VAR_PAPERLESS_TOKEN: ENC[AES256_GCM,data:qnOeS+fzZBQAu3Oafz8iolTwGirdYB3VVC0fIz5rrzMilMidqMjUpflTl9X7PVAmhy5nXMpK9ug=,iv:469P4GcL+9BBrYlZcMsqRxQGfstMwQdb1o30ptw29S0=,tag:vVIV2xuXLOoT9ziUhCfEUw==,type:str]
    HOMEPAGE_VAR_CHANGEDETECTION_API_TOKEN: ENC[AES256_GCM,data:K4yimEuuDWVQnQ/RwDbSX1cCIRJhigqelQiuKo+LTXpyFG4ooU1GYq71S8A=,iv:RFifIB1Dr8+ypsKXtUMMllnyoLLfQjVlCnkSqhk/Yb8=,tag:v3VEUpWF46Zr4iVq3Eg5+w==,type:str]
    HOMEPAGE_VAR_PHOTOPRISM_USERNAME: ENC[AES256_GCM,data:4LikOy5nbOg=,iv:W+O/OiMjlaVRCfhl8rN5KYgAc8MEaWuF5rIAO3nb7wI=,tag:RmUpHydA07QDtLvE3/SuPA==,type:str]
    HOMEPAGE_VAR_PHOTOPRISM_PASSWORD: ENC[AES256_GCM,data:fU2b9lgZX9Rpbv6eeQXO4gztrxJl185gpqRQXog5UgYeagUJ01VG4Q==,iv:dpLjjgK6l4l9rTFVvFJ3SEZFleME5XBIXj7roMnd020=,tag:h9BUSZMWfsna8ke4xvIP8A==,type:str]
    HOMEPAGE_VAR_CALIBREWEB_USERNAME: ENC[AES256_GCM,data:MR+4MQtfpJ4=,iv:lywqj+cLnFoqRFS0HiMXHWaNIDlpvu07XNfJNXy0oFQ=,tag:h7XgTK20IECjEFcsODZpmQ==,type:str]
    HOMEPAGE_VAR_CALIBREWEB_PASSWORD: ENC[AES256_GCM,data:wdAj9b4kom2LyMtr,iv:FfdTg4GI5ZbmsoG7RCiFHQ0d0Be6u5TE1RsFtU3fBp8=,tag:4PyH2Jp6dZKepKyPBeAKKw==,type:str]
kind: Secret
metadata:
    name: app-keys
    namespace: homepage
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e764qpphm5nlzp04qf6zcq8f400390d9wmzramq84hqp60k6qyvqsvgg45
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmL0dyNnhoUFA5Szd6OTN0
            aFlJcFdCb0w3RTZrdENESk9DTGFtclhWM2c0CkJnN3g4RVlJQWlrcmhmM0tVSEF5
            RmtuRHRiQkZmTm5Wemd2NStoNmZZNjQKLS0tIGJBRnc0ZWhTeFNUOWpTT2s3Rnli
            ZGQ1bXRlYTZZdklodHB0UzF1dkV1VEEKSC/V5zdU9qic9DJd8qBGdONrA7y9FtmZ
            q5x9vW/FavAsmIq2kvH2mUuixhvbP6UIP0u254/hu1qiXwG5gKeHkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T02:27:28Z"
    mac: ENC[AES256_GCM,data:jkbje9MHEKWRjpKqZkHuMP9NqXbP0uXHvh9IaJqRrB6yfZKtXGIowtOaFZqXH1oCzFuHhxofRbWsllXZyN2i4vSOBj4gK3HQs+6TLxE9PIMulNbI6XB2vVBC/k+kGZKbxLv+l5tb1JikLSs822RA7PfR/KHaLMP43rYa3zce/M0=,iv:nSPJHTMmYvOTmjrGlBnWG5tQ5qCJzh6A4B6ez8n/ps4=,tag:aPb7+f8ASyOFcH9WJHw7xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
