crds:
  # -- Whether the helm chart should create and update the CRDs. If false, the CRDs must be
  # managed independently with deploy/examples/crds.yaml.
  # **WARNING** Only set during first deployment. If later disabled the cluster may be DESTROYED.
  # If the CRDs are deleted in this case, see
  # [the disaster recovery guide](https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#restoring-crds-after-deletion)
  # to restore them.
  enabled: false
resources:
  requests:
    cpu: 109m
    memory: 204M
  limits:
    memory: 453M

# nodeSelector:
#  hermleigh.home/jbod: true

csi:
  enableNFSSnapshotter: false
  provisionerReplicas: 1

monitoring:
  enabled: true

