apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage

resources:
  - "github.com/rancher/local-path-provisioner/deploy?ref=v0.0.26"
  - ./storage-classes.yaml

patches:
  - patch: |-
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: local-path-config
        namespace: local-path-storage
      data:
        config.json: |-
          {
            "nodePathMap":[
              {
                "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                "paths":["/opt/local-path-provisioner"]
              },
              {
                "node": "parche",
                "paths": [
                  "/srv/cluster/volumes",
                  "/videos/volumes",
                  "/share/volumes"
                ]
              }
            ]
          }
  - patch: |-
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
      reclaimPolicy: Retain
      parameters:
        nodePath: /srv/cluster/volumes
