app:
  django:
    existingDatabase:
      enabled: true
      host: cnpg-cluster-rw.db.svc
      existingSecret:
        name: wger-secret
        dbuserKey: DJANGO_DB_USER
        dbpsKey: DJANGO_DB_PASSWORD
  environment:
    - name: DJANGO_CACHE_LOCATION
      value: "redis://redis-master.db.svc:6379/1"

ingress:
  enabled: true
  ingressClassName: nginx
  url: fit.hermleigh.cc
  tls: true
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Wger
    gethomepage.dev/description: "Personal workout/food tracker"
    gethomepage.dev/icon: "wger.svg"
    gethomepage.dev/group: "Apps & Services"
    cert-manager.io/cluster-issuer: ca-issuer

redis:
  storage:
    className: local-path

postgres:
  enabled: false
