#
# Ansible managed
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: qbittorrent-config
    namespace: downloads
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  capacity:
    storage: 153G
  local:
    path: /srv/cluster/volumes/downloads/qbittorrent/qbittorrent-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - parche
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: downloads
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 153G
  storageClassName: local-storage
  volumeName: qbittorrent-config
