#
# Ansible managed
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql
    namespace: db
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  capacity:
    storage: 153G
  local:
    path: /srv/cluster/volumes/db/mysql/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - parche
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: db
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 153G
  storageClassName: local-storage
  volumeName: mysql
