apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        meta.helm.sh/release-name: mysql
        meta.helm.sh/release-namespace: db
    labels:
        app.kubernetes.io/instance: mysql
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mysql
        helm.sh/chart: mysql-9.10.1
    name: mysql
    namespace: db
data:
    mysql-password: MG9DTmhVTEtEcQ==
    mysql-root-password: ZnBGT1VydTVKMQ==
